# Etapa de construcción de la aplicación React
FROM node:20.14 AS react

WORKDIR /app
COPY src/frontend/package.json src/frontend/package-lock.json ./
RUN npm install

# Variables de entorno para React
ARG MASTERNOTE_API_URL
ARG MASTERNOTE_API_URL
ARG MASTERNOTE_DISCORD_CLIENT_ID

COPY src/frontend ./
RUN echo "VITE_API_URL=$MASTERNOTE_API_URL" > .env.local \
    && echo "VITE_DISCORD_CLIENT_ID=$MASTERNOTE_DISCORD_CLIENT_ID" >> .env.local
RUN npm run build

# Servidor nginx para servir la aplicación React
FROM nginx:alpine AS frontend

COPY src/frontend/default.conf /etc/nginx/conf.d/default.conf
COPY --from=react /app/dist /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
