<?php

return [
    'topics' => [
        "Mathematics",
        "Science",
        "History",
        "Literature",
        "Art",
        "Music",
        "Computer Science",
        "Languages",
        "Geography",
        "Philosophy",
        "Economics",
        "Psychology",
        "Sociology",
        "Physical Education",
        "Chemistry",
        "Biology",
        "Environmental Studies",
        "Engineering",
        "Business Studies",
        "Political Science",
        "Health and Wellness",
        "Civics",
        "Religious Studies",
        "Media Studies",
        "Astronomy",
        "Anthropology",
        "Cultural Studies",
        "Nutrition",
        "Law",
        "Architecture",
        "Drama and Theater",
        "Film Studies",
        "Gender Studies",
        "Military History",
        "Technology",
        "Fashion",
        "Hospitality Management",
        "Aviation",
        "Journalism",
        "Marine Biology",
        "Social Work",
        "Urban Planning",
        "Foreign Policy",
        "Artificial Intelligence",
        "Robotics",
        "Ethics",
        "Game Design",
        "Ecology",
        "Meteorology",
        "Cryptocurrency",
        "Data Science",
        "Entrepreneurship",
        "Folklore",
        "Mythology",
        "Space Exploration",
        "Zoology",
        "Paleontology",
        "Oceanography",
        "Sustainability",
        "Forensic Science",
        "Geology",
        "Music Theory",
        "Yoga and Meditation",
        "Dance",
        "Photography",
        "Sustainable Agriculture",
        "Astrophysics",
        "Personal Finance",
        "Public Speaking",
        "Self-Improvement",
        "Time Management",
        "Graphic Design",
        "Interior Design",
        "Welding",
        "Automotive Technology",
        "Electrical Engineering",
        "Renewable Energy",
        "Fashion Design",
        "Fitness Training",
        "Interior Decorating",
        "Creative Writing",
        "Gardening",
        "Cooking",
        "Child Development",
        "Parenting",
        "Criminal Justice",
        "Emergency Management",
        "Firefighting",
        "Public Administration",
        "Veterinary Science",
        "Pharmacology",
        "Dentistry",
        "Physical Therapy",
        "Nursing",
        "Medicine",
        "Dietetics",
        "Sports Management",
        "Sports Medicine",
        "Athletic Training",
        "Mental Health",
        "Addiction Counseling",
        "Social Justice",
        "Environmental Law",
        "Human Rights",
        "Conflict Resolution",
        "Green Building",
        "Industrial Design",
        "Human Anatomy",
        "Cell Biology",
        "Genetics",
        "Microbiology",
        "Immunology",
        "Neuroscience",
        "Quantum Physics",
        "Materials Science",
        "Cybersecurity",
        "Network Administration",
        "Cloud Computing",
        "Machine Learning",
        "Virtual Reality",
        "Augmented Reality",
        "Blockchain Technology",
        "Internet of Things",
        "Digital Marketing",
        "Content Strategy",
        "Search Engine Optimization",
        "User Experience Design",
        "User Interface Design",
        "Product Management",
        "Project Management",
        "Agile Methodologies",
        "Scrum",
        "Kanban",
        "Six Sigma",
        "Lean Manufacturing",
        "Quality Management",
        "Supply Chain Management",
        "Logistics",
        "Inventory Management",
        "Customer Relationship Management",
        "Sales Management",
        "Retail Management",
        "Human Resource Management",
        "Organizational Behavior",
        "Leadership Development",
        "Change Management",
        "Conflict Management",
        "Performance Management",
        "Talent Management",
        "Employee Training",
        "Compensation and Benefits",
        "Recruitment and Selection",
        "Workplace Diversity",
        "Employment Law",
        "Labor Relations",
        "International Business",
        "Cross-Cultural Management",
        "Globalization",
        "International Trade",
        "Export-Import Management",
        "Foreign Exchange Markets",
        "International Marketing",
        "International Finance",
        "Global Supply Chain Management",
        "Global Business Strategy"
    ]
];
